version: '3'
services:
  web:
    image: nzeong/gotcha:latest
    env_file:
      - .env
    expose:
      - 8080
    ports:
      - "8080:8080"
    tty: true
    restart: "always"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod